stages:
  - build

build and test linux:
  stage: build
  tags:
    - cura
    - linux
    - docker
  image: registry.gitlab.com/ultimaker/cura/cura-build-environment:centos7
  script:
    - docker/build.sh
  artifacts:
    paths:
      - build

build and test windows:
  stage: build
  tags:
    - cura
    - windows
    - powershell
  variables:
    IMAGE: registry.gitlab.com/ultimaker/cura/cura-build-environment:windows-core-1809
  script:
    - docker\build.ps1
  artifacts:
    paths:
      - build
